#############################################################################
# Makefile for building: test
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  main.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile main.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DSTYLES_DIR=/home/kurumi/download/projects/MainWindow/styles -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++2a -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -I/usr/include/eigen3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = test1.0.0
DISTDIR = /home/kurumi/download/projects/MainWindow/build/test1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5Svg.so /usr/lib/x86_64-linux-gnu/libQt5Charts.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/calc/analyze_ac.cpp \
		src/calc/analyze_context.cpp \
		src/calc/analyze_dc.cpp \
		src/calc/analyze_op.cpp \
		src/calc/analyze_tran.cpp \
		src/chart/mychart.cpp \
		src/chart/plot_context.cpp \
		src/chart/plot_manager.cpp \
		src/chart/print_manager.cpp \
		src/circuit/circuit.cpp \
		src/console/myconsole.cpp \
		src/devices/item/capacitor.cpp \
		src/devices/item/cccs.cpp \
		src/devices/item/ccvs.cpp \
		src/devices/item/diode.cpp \
		src/devices/item/inductor.cpp \
		src/devices/item/isource.cpp \
		src/devices/item/mosfet.cpp \
		src/devices/item/resistor.cpp \
		src/devices/item/vccs.cpp \
		src/devices/item/vcvs.cpp \
		src/devices/item/vsource.cpp \
		src/devices/nonlinear_device.cpp \
		src/devices/base_device.cpp \
		src/devices/dynamic_device.cpp \
		src/devices/source_device.cpp \
		src/global/global.cpp \
		src/ui/aboutwindow.cpp \
		src/ui/mymainwindow.cpp \
		src/parser/parser.cpp \
		src/parser/scanner.cpp \
		src/qss/QmlStyleUrlInterceptor.cpp \
		src/qss/QtAdvancedStylesheet.cpp build/qrc_mainwindow.cpp \
		build/moc_mychart.cpp \
		build/moc_aboutwindow.cpp \
		build/moc_mymainwindow.cpp \
		build/moc_QtAdvancedStylesheet.cpp
OBJECTS       = build/main.o \
		build/analyze_ac.o \
		build/analyze_context.o \
		build/analyze_dc.o \
		build/analyze_op.o \
		build/analyze_tran.o \
		build/mychart.o \
		build/plot_context.o \
		build/plot_manager.o \
		build/print_manager.o \
		build/circuit.o \
		build/myconsole.o \
		build/capacitor.o \
		build/cccs.o \
		build/ccvs.o \
		build/diode.o \
		build/inductor.o \
		build/isource.o \
		build/mosfet.o \
		build/resistor.o \
		build/vccs.o \
		build/vcvs.o \
		build/vsource.o \
		build/nonlinear_device.o \
		build/base_device.o \
		build/dynamic_device.o \
		build/source_device.o \
		build/global.o \
		build/aboutwindow.o \
		build/mymainwindow.o \
		build/parser.o \
		build/scanner.o \
		build/QmlStyleUrlInterceptor.o \
		build/QtAdvancedStylesheet.o \
		build/qrc_mainwindow.o \
		build/moc_mychart.o \
		build/moc_aboutwindow.o \
		build/moc_mymainwindow.o \
		build/moc_QtAdvancedStylesheet.o
DIST          = src/parser/parser.output \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		main.pro src/calc/analyze_ac.h \
		src/calc/analyze_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_entry.h \
		src/calc/analyze_manager.hpp \
		src/calc/analyze_op.h \
		src/calc/analyze_tran.h \
		src/calc/iteration_context.hpp \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/chart/plot_manager.h \
		src/chart/print_manager.h \
		src/circuit/circuit.h \
		src/circuit/circuit_node.h \
		src/cmds/ac_dc.hpp \
		src/cmds/option.hpp \
		src/cmds/print.hpp \
		src/cmds/pulse.hpp \
		src/console/myconsole.h \
		src/devices/item/capacitor.h \
		src/devices/item/cccs.h \
		src/devices/item/ccvs.h \
		src/devices/item/diode.h \
		src/devices/item/inductor.h \
		src/devices/item/isource.h \
		src/devices/item/mosfet.h \
		src/devices/item/resistor.h \
		src/devices/item/vccs.h \
		src/devices/item/vcvs.h \
		src/devices/item/vsource.h \
		src/devices/nonlinear_device.h \
		src/devices/base_device.h \
		src/devices/dynamic_device.h \
		src/devices/source_device.h \
		src/global/global.h \
		src/ui/aboutwindow.h \
		src/ui/mymainwindow.h \
		src/parser/location.hh \
		src/parser/parser.hpp \
		src/parser/position.hh \
		src/parser/scanner.hpp \
		src/parser/sp.l \
		src/parser/sp.y \
		src/parser/stack.hh \
		src/qss/QmlStyleUrlInterceptor.h \
		src/qss/QtAdvancedStylesheet.h \
		src/qss/acss_globals.h \
		src/utils/SpiceHighlighter.hpp src/main.cpp \
		src/calc/analyze_ac.cpp \
		src/calc/analyze_context.cpp \
		src/calc/analyze_dc.cpp \
		src/calc/analyze_op.cpp \
		src/calc/analyze_tran.cpp \
		src/chart/mychart.cpp \
		src/chart/plot_context.cpp \
		src/chart/plot_manager.cpp \
		src/chart/print_manager.cpp \
		src/circuit/circuit.cpp \
		src/console/myconsole.cpp \
		src/devices/item/capacitor.cpp \
		src/devices/item/cccs.cpp \
		src/devices/item/ccvs.cpp \
		src/devices/item/diode.cpp \
		src/devices/item/inductor.cpp \
		src/devices/item/isource.cpp \
		src/devices/item/mosfet.cpp \
		src/devices/item/resistor.cpp \
		src/devices/item/vccs.cpp \
		src/devices/item/vcvs.cpp \
		src/devices/item/vsource.cpp \
		src/devices/nonlinear_device.cpp \
		src/devices/base_device.cpp \
		src/devices/dynamic_device.cpp \
		src/devices/source_device.cpp \
		src/global/global.cpp \
		src/ui/aboutwindow.cpp \
		src/ui/mymainwindow.cpp \
		src/parser/parser.cpp \
		src/parser/scanner.cpp \
		src/qss/QmlStyleUrlInterceptor.cpp \
		src/qss/QtAdvancedStylesheet.cpp
QMAKE_TARGET  = test
DESTDIR       = 
TARGET        = test


first: all
####### Build rules

test: build/ui_mainwindow2.h build/ui_mychart.h build/ui_aboutwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: main.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		main.pro \
		src/ui/mainwindow.qrc
	$(QMAKE) -o Makefile main.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
main.pro:
src/ui/mainwindow.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile main.pro

qmake_all: FORCE


all: Makefile test

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/ui/mainwindow.qrc src/ui/mainwindow.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/calc/analyze_ac.h src/calc/analyze_context.h src/calc/analyze_dc.h src/calc/analyze_entry.h src/calc/analyze_manager.hpp src/calc/analyze_op.h src/calc/analyze_tran.h src/calc/iteration_context.hpp src/chart/mychart.h src/chart/plot_context.h src/chart/plot_manager.h src/chart/print_manager.h src/circuit/circuit.h src/circuit/circuit_node.h src/cmds/ac_dc.hpp src/cmds/option.hpp src/cmds/print.hpp src/cmds/pulse.hpp src/console/myconsole.h src/devices/item/capacitor.h src/devices/item/cccs.h src/devices/item/ccvs.h src/devices/item/diode.h src/devices/item/inductor.h src/devices/item/isource.h src/devices/item/mosfet.h src/devices/item/resistor.h src/devices/item/vccs.h src/devices/item/vcvs.h src/devices/item/vsource.h src/devices/nonlinear_device.h src/devices/base_device.h src/devices/dynamic_device.h src/devices/source_device.h src/global/global.h src/ui/aboutwindow.h src/ui/mymainwindow.h src/parser/location.hh src/parser/parser.hpp src/parser/position.hh src/parser/scanner.hpp src/parser/sp.l src/parser/sp.y src/parser/stack.hh src/qss/QmlStyleUrlInterceptor.h src/qss/QtAdvancedStylesheet.h src/qss/acss_globals.h src/utils/SpiceHighlighter.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/calc/analyze_ac.cpp src/calc/analyze_context.cpp src/calc/analyze_dc.cpp src/calc/analyze_op.cpp src/calc/analyze_tran.cpp src/chart/mychart.cpp src/chart/plot_context.cpp src/chart/plot_manager.cpp src/chart/print_manager.cpp src/circuit/circuit.cpp src/console/myconsole.cpp src/devices/item/capacitor.cpp src/devices/item/cccs.cpp src/devices/item/ccvs.cpp src/devices/item/diode.cpp src/devices/item/inductor.cpp src/devices/item/isource.cpp src/devices/item/mosfet.cpp src/devices/item/resistor.cpp src/devices/item/vccs.cpp src/devices/item/vcvs.cpp src/devices/item/vsource.cpp src/devices/nonlinear_device.cpp src/devices/base_device.cpp src/devices/dynamic_device.cpp src/devices/source_device.cpp src/global/global.cpp src/ui/aboutwindow.cpp src/ui/mymainwindow.cpp src/parser/parser.cpp src/parser/scanner.cpp src/qss/QmlStyleUrlInterceptor.cpp src/qss/QtAdvancedStylesheet.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow2.ui mychart.ui src/ui/aboutwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/qrc_mainwindow.cpp build/qrc_mainwindow.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/qrc_mainwindow.cpp build/qrc_mainwindow.cpp
build/qrc_mainwindow.cpp: src/ui/mainwindow.qrc \
		/usr/lib/qt5/bin/rcc \
		src/images/editdelete.png \
		src/images/spice-1.svg \
		src/images/chip.svg \
		src/images/newfile.svg \
		src/images/filesaveall.png \
		src/images/fileclose.png \
		src/images/editpaste.png \
		src/images/about.svg \
		src/images/save.svg \
		src/images/editcut.png \
		src/images/editcopy.png \
		src/images/filesave.png \
		src/images/fileprint.png \
		src/images/open.svg \
		src/images/filenew.png \
		src/images/fileopen.png \
		src/images/filesaveas.png \
		src/images/saveas.svg
	/usr/lib/qt5/bin/rcc -name mainwindow src/ui/mainwindow.qrc -o build/qrc_mainwindow.cpp

build/qrc_mainwindow.cpp: src/ui/mainwindow.qrc \
		/usr/lib/qt5/bin/rcc \
		src/images/editdelete.png \
		src/images/spice-1.svg \
		src/images/chip.svg \
		src/images/newfile.svg \
		src/images/filesaveall.png \
		src/images/fileclose.png \
		src/images/editpaste.png \
		src/images/about.svg \
		src/images/save.svg \
		src/images/editcut.png \
		src/images/editcopy.png \
		src/images/filesave.png \
		src/images/fileprint.png \
		src/images/open.svg \
		src/images/filenew.png \
		src/images/fileopen.png \
		src/images/filesaveas.png \
		src/images/saveas.svg
	/usr/lib/qt5/bin/rcc -name mainwindow src/ui/mainwindow.qrc -o build/qrc_mainwindow.cpp

compiler_moc_predefs_make_all: build/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc_predefs.h
build/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++2a -Wall -Wextra -dM -E -o build/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc_mychart.cpp build/moc_aboutwindow.cpp build/moc_mymainwindow.cpp build/moc_QtAdvancedStylesheet.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_mychart.cpp build/moc_aboutwindow.cpp build/moc_mymainwindow.cpp build/moc_QtAdvancedStylesheet.cpp
build/moc_mychart.cpp: src/chart/mychart.h \
		src/chart/plot_context.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kurumi/download/projects/MainWindow/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kurumi/download/projects/MainWindow -I/home/kurumi/download/projects/MainWindow/src -I/usr/include/eigen3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/chart/mychart.h -o build/moc_mychart.cpp

build/moc_aboutwindow.cpp: src/ui/aboutwindow.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kurumi/download/projects/MainWindow/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kurumi/download/projects/MainWindow -I/home/kurumi/download/projects/MainWindow/src -I/usr/include/eigen3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ui/aboutwindow.h -o build/moc_aboutwindow.cpp

build/moc_mymainwindow.cpp: src/ui/mymainwindow.h \
		build/ui_mainwindow2.h \
		src/qss/QtAdvancedStylesheet.h \
		src/qss/acss_globals.h \
		src/utils/SpiceHighlighter.hpp \
		src/global/global.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_manager.hpp \
		src/calc/analyze_entry.h \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kurumi/download/projects/MainWindow/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kurumi/download/projects/MainWindow -I/home/kurumi/download/projects/MainWindow/src -I/usr/include/eigen3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ui/mymainwindow.h -o build/moc_mymainwindow.cpp

build/moc_QtAdvancedStylesheet.cpp: src/qss/QtAdvancedStylesheet.h \
		src/qss/acss_globals.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kurumi/download/projects/MainWindow/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kurumi/download/projects/MainWindow -I/home/kurumi/download/projects/MainWindow/src -I/usr/include/eigen3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/qss/QtAdvancedStylesheet.h -o build/moc_QtAdvancedStylesheet.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_mainwindow2.h build/ui_mychart.h build/ui_aboutwindow.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_mainwindow2.h build/ui_mychart.h build/ui_aboutwindow.h
build/ui_mainwindow2.h: mainwindow2.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow2.ui -o build/ui_mainwindow2.h

build/ui_mychart.h: mychart.ui \
		/usr/lib/qt5/bin/uic \
		/usr/include/x86_64-linux-gnu/qt5/QtCharts/qchartview.h
	/usr/lib/qt5/bin/uic mychart.ui -o build/ui_mychart.h

build/ui_aboutwindow.h: src/ui/aboutwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/aboutwindow.ui -o build/ui_aboutwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/main.o: src/main.cpp src/ui/mymainwindow.h \
		build/ui_mainwindow2.h \
		src/qss/QtAdvancedStylesheet.h \
		src/qss/acss_globals.h \
		src/utils/SpiceHighlighter.hpp \
		src/global/global.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_manager.hpp \
		src/calc/analyze_entry.h \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/analyze_ac.o: src/calc/analyze_ac.cpp src/console/myconsole.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_entry.h \
		src/global/global.h \
		src/calc/analyze_manager.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h \
		src/chart/plot_manager.h \
		src/chart/print_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/analyze_ac.o src/calc/analyze_ac.cpp

build/analyze_context.o: src/calc/analyze_context.cpp src/circuit/circuit.h \
		src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/analyze_context.o src/calc/analyze_context.cpp

build/analyze_dc.o: src/calc/analyze_dc.cpp src/console/myconsole.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_entry.h \
		src/global/global.h \
		src/calc/analyze_manager.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h \
		src/chart/plot_manager.h \
		src/chart/print_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/analyze_dc.o src/calc/analyze_dc.cpp

build/analyze_op.o: src/calc/analyze_op.cpp src/console/myconsole.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_entry.h \
		src/global/global.h \
		src/calc/analyze_manager.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h \
		src/chart/plot_manager.h \
		src/chart/print_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/analyze_op.o src/calc/analyze_op.cpp

build/analyze_tran.o: src/calc/analyze_tran.cpp src/console/myconsole.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_entry.h \
		src/global/global.h \
		src/calc/analyze_manager.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h \
		src/chart/plot_manager.h \
		src/chart/print_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/analyze_tran.o src/calc/analyze_tran.cpp

build/mychart.o: src/chart/mychart.cpp src/chart/mychart.h \
		src/chart/plot_context.h \
		build/ui_mychart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mychart.o src/chart/mychart.cpp

build/plot_context.o: src/chart/plot_context.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/plot_context.o src/chart/plot_context.cpp

build/plot_manager.o: src/chart/plot_manager.cpp src/console/myconsole.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_entry.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/global/global.h \
		src/calc/analyze_manager.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h \
		src/chart/plot_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/plot_manager.o src/chart/plot_manager.cpp

build/print_manager.o: src/chart/print_manager.cpp src/console/myconsole.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_entry.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/global/global.h \
		src/calc/analyze_manager.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h \
		src/chart/print_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/print_manager.o src/chart/print_manager.cpp

build/circuit.o: src/circuit/circuit.cpp src/circuit/circuit.h \
		src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/circuit.o src/circuit/circuit.cpp

build/myconsole.o: src/console/myconsole.cpp src/console/myconsole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/myconsole.o src/console/myconsole.cpp

build/capacitor.o: src/devices/item/capacitor.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/capacitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/capacitor.o src/devices/item/capacitor.cpp

build/cccs.o: src/devices/item/cccs.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/cccs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/cccs.o src/devices/item/cccs.cpp

build/ccvs.o: src/devices/item/ccvs.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/ccvs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ccvs.o src/devices/item/ccvs.cpp

build/diode.o: src/devices/item/diode.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/diode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/diode.o src/devices/item/diode.cpp

build/inductor.o: src/devices/item/inductor.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/inductor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/inductor.o src/devices/item/inductor.cpp

build/isource.o: src/devices/item/isource.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/isource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/isource.o src/devices/item/isource.cpp

build/mosfet.o: src/devices/item/mosfet.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/mosfet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mosfet.o src/devices/item/mosfet.cpp

build/resistor.o: src/devices/item/resistor.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/resistor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/resistor.o src/devices/item/resistor.cpp

build/vccs.o: src/devices/item/vccs.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/vccs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/vccs.o src/devices/item/vccs.cpp

build/vcvs.o: src/devices/item/vcvs.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/vcvs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/vcvs.o src/devices/item/vcvs.cpp

build/vsource.o: src/devices/item/vsource.cpp src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/item/vsource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/vsource.o src/devices/item/vsource.cpp

build/nonlinear_device.o: src/devices/nonlinear_device.cpp src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/nonlinear_device.h \
		src/devices/base_device.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/nonlinear_device.o src/devices/nonlinear_device.cpp

build/base_device.o: src/devices/base_device.cpp src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/base_device.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/base_device.o src/devices/base_device.cpp

build/dynamic_device.o: src/devices/dynamic_device.cpp src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/dynamic_device.h \
		src/devices/base_device.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dynamic_device.o src/devices/dynamic_device.cpp

build/source_device.o: src/devices/source_device.cpp src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/devices/source_device.h \
		src/devices/base_device.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/source_device.o src/devices/source_device.cpp

build/global.o: src/global/global.cpp src/circuit/circuit.h \
		src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_manager.hpp \
		src/calc/analyze_entry.h \
		src/global/global.h \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/global.o src/global/global.cpp

build/aboutwindow.o: src/ui/aboutwindow.cpp src/ui/aboutwindow.h \
		build/ui_aboutwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/aboutwindow.o src/ui/aboutwindow.cpp

build/mymainwindow.o: src/ui/mymainwindow.cpp src/ui/mymainwindow.h \
		build/ui_mainwindow2.h \
		src/qss/QtAdvancedStylesheet.h \
		src/qss/acss_globals.h \
		src/utils/SpiceHighlighter.hpp \
		src/global/global.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/console/myconsole.h \
		src/circuit/circuit_node.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/cmds/plot.hpp \
		src/cmds/print.hpp \
		src/calc/analyze_manager.hpp \
		src/calc/analyze_entry.h \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/calc/analyze_ac.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h \
		src/parser/scanner.hpp \
		src/parser/parser.hpp \
		src/ui/aboutwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mymainwindow.o src/ui/mymainwindow.cpp

build/parser.o: src/parser/parser.cpp src/parser/scanner.hpp \
		src/console/myconsole.h \
		src/cmds/plot.hpp \
		src/circuit/circuit_node.h \
		src/cmds/print.hpp \
		src/cmds/pulse.hpp \
		src/cmds/sinusoid.hpp \
		src/global/global.h \
		src/circuit/circuit.h \
		src/devices/base_device.h \
		src/calc/analyze_context.h \
		src/cmds/ac_dc.hpp \
		src/calc/iteration_context.hpp \
		src/cmds/option.hpp \
		src/cmds/tran.hpp \
		src/calc/analyze_manager.hpp \
		src/calc/analyze_entry.h \
		src/devices/dynamic_device.h \
		src/devices/nonlinear_device.h \
		src/devices/source_device.h \
		src/calc/analyze_ac.h \
		src/chart/mychart.h \
		src/chart/plot_context.h \
		src/calc/analyze_dc.h \
		src/calc/analyze_tran.h \
		src/calc/analyze_op.h \
		src/devices/item/resistor.h \
		src/devices/item/capacitor.h \
		src/devices/item/inductor.h \
		src/devices/item/isource.h \
		src/devices/item/vsource.h \
		src/devices/item/vcvs.h \
		src/devices/item/vccs.h \
		src/devices/item/ccvs.h \
		src/devices/item/cccs.h \
		src/devices/item/diode.h \
		src/devices/item/mosfet.h \
		src/parser/parser.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/parser.o src/parser/parser.cpp

build/scanner.o: src/parser/scanner.cpp src/parser/parser.hpp \
		src/console/myconsole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/scanner.o src/parser/scanner.cpp

build/QmlStyleUrlInterceptor.o: src/qss/QmlStyleUrlInterceptor.cpp src/qss/QmlStyleUrlInterceptor.h \
		src/qss/acss_globals.h \
		src/qss/QtAdvancedStylesheet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QmlStyleUrlInterceptor.o src/qss/QmlStyleUrlInterceptor.cpp

build/QtAdvancedStylesheet.o: src/qss/QtAdvancedStylesheet.cpp src/qss/QtAdvancedStylesheet.h \
		src/qss/acss_globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QtAdvancedStylesheet.o src/qss/QtAdvancedStylesheet.cpp

build/qrc_mainwindow.o: build/qrc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_mainwindow.o build/qrc_mainwindow.cpp

build/moc_mychart.o: build/moc_mychart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mychart.o build/moc_mychart.cpp

build/moc_aboutwindow.o: build/moc_aboutwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_aboutwindow.o build/moc_aboutwindow.cpp

build/moc_mymainwindow.o: build/moc_mymainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mymainwindow.o build/moc_mymainwindow.cpp

build/moc_QtAdvancedStylesheet.o: build/moc_QtAdvancedStylesheet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_QtAdvancedStylesheet.o build/moc_QtAdvancedStylesheet.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

